# fly.toml app configuration file generated for target-onchain on 2024-06-16T21:51:37-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'target-onchain'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3000"
  SHOPIFY_APP_URL = "https://target-onchain.fly.dev"
  SHOPIFY_API_KEY = "b8e625d85b72fe571087d22cd7b7684d"
  SCOPES = "read_product_listings,unauthenticated_read_checkouts,write_resource_feedbacks"
  TARGET_ONCHAIN_URL = "https://target-onchain-app.vercel.app"
  CLERK_URL = "https://possible-ocelot-87.clerk.accounts.dev"
  APP_NAME = "target-onchain"
